In [ ]:
import numpy as np

X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0,1,1,0]]).T
# Change so always using this same X and y.


In [ ]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
y

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
# https://iamtrask.github.io/2015/07/12/basic-python-network/

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(10000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

print(l2)

[[0.00788842]
 [0.99156613]
 [0.98914719]
 [0.01190871]]


In [ ]:
l2_delta

array([[-0.09712517],
       [ 0.14411524],
       [ 0.14211822],
       [-0.09924881]])

In [ ]:
import tensorflow as tf

model = tf.keras.Sequential([
        tf.keras.layers.Dense(4, activation='sigmoid', input_shape=(3,)),  # 4,3 -> 4,4
        tf.keras.layers.Dense(1, activation='sigmoid')]) #4,4. -> 4,1

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1), loss='mean_squared_error')
model.fit(X, y, epochs=500, verbose=0)
model.predict(X)


1/1 [==============================] - 0s 52ms/step


array([[0.24264789],
       [0.6182925 ],
       [0.76604456],
       [0.36658302]], dtype=float32)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim


x_data = torch.tensor(X, dtype=torch.float32)
y_data = torch.tensor(y, dtype=torch.float32)

class XORModel(nn.Module):
    def __init__(self):
        super(XORModel, self).__init__()
        self.fc1 = nn.Linear(3, 4)
        self.fc2 = nn.Linear(4, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        x = self.sigmoid(self.fc1(x))
        x = self.sigmoid(self.fc2(x))
        return x

model = XORModel()
optimizer = optim.SGD(model.parameters(), lr=1)
criterion = nn.MSELoss()
# Train the model
for epoch in range(5000):
    optimizer.zero_grad()
    output = model(x_data)
    loss = criterion(output, y_data)
    print(loss)
    loss.backward()
    optimizer.step()

# Test the model
predictions = model(x_data).detach().numpy()
rounded_predictions = np.round(predictions)

print('Predictions:')
for i in range(len(x_data)):
    print(x_data[i].numpy(),  predictions[i])

Streaming output truncated to the last 5000 lines.
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2502, grad_fn=<MseLossBackward0>)
tensor(0.2501, grad_fn=<MseLossBackward0>)
tensor(0.2501, grad_fn=<MseLossBackward0>)
tensor(0.2501, grad_fn=<MseLossBackward0>)
tensor(0.2501, grad_fn=<MseLossBackward0>)
tensor(0.2501, grad_fn=<MseLossBackward0>)
tensor(0.2501, grad_fn=<MseLossBackward0>)
ten

In [ ]:
# https://towardsdatascience.com/three-ways-to-build-a-neural-network-in-pytorch-8cea49f9a61a
###########
model = nn.Sequential(
    nn.Linear(16, 12),
    nn.ReLU(),
    nn.Linear(12, 10),
    nn.ReLU(),
    nn.Linear(10, 1),
    nn.Sigmoid()
)
###########
class MyNetwork(nn.Module):
    def __init__(self):
        # call constructor from superclass
        super().__init__()

        # define network layers
        self.fc1 = nn.Linear(16, 12)
        self.fc2 = nn.Linear(12, 10)
        self.fc3 = nn.Linear(10, 1)

    def forward(self, x):
        # define forward pass
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x
#########
features = torch.randn(1, 16)

W1 = torch.randn((16, 12), requires_grad=True)
W2 = torch.randn((12, 10), requires_grad=True)
W3 = torch.randn((10, 1), requires_grad=True)

B1 = torch.randn((12), requires_grad=True)
B2 = torch.randn((10), requires_grad=True)
B3 = torch.randn((1), requires_grad=True)

h1 = F.relu((features @ W1) + B1)
h2 = F.relu((h1 @ W2) + B2)
output = torch.sigmoid((h2 @ W3) + B3)

#######

https://github.com/google-research/tuning_playbook/blob/main/README.md#choosing-the-optimizer

https://github.com/google-research/tuning_playbook

In [ ]:
import torch
x, y = torch.tensor(np.array([ [0.,0.,1.],[0.,1.,1.],[1.,0.,1.],[1.,1.,1.] ])),  torch.tensor(np.array([[0.,1.,1.,0.]]).T)
#X = torch.tensor(X)
#y = torch.tensor(y)

w = torch.tensor(np.array([.1,.1,.1]), requires_grad=True)
loss = (((w*x)-y)**2)
loss.backward()

with torch.no_grad():
  w -= w.grad * .1

By:

Joaquin Dominguez(https://www.linkedin.com/in/joaquin-dominguez1992/)

Richard Kim(https://www.linkedin.com/in/richard-y-kim/)

John Santerre(https://www.linkedin.com/in/john-santerre-phd-91609b6/)

