# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:
    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [2]:
my_array1 = np.array([1, 2, 3, 4])
print('Shape of my_array1:', my_array1.shape)
print('Data types of my_array1:', my_array1.dtype)

my_array2 = np.array(['A',1,'B',2])
print('Shape of my_array2:', my_array2.shape)
print('Data types of my_array2:', my_array2.dtype)

# In an array with element of mixed data types, the data types will be cast to
# a data type that can accommodate all elements. In this case, the type is a
# Unicode type with length 21

Shape of my_array1: (4,)
Data types of my_array1: int64
Shape of my_array2: (4,)
Data types of my_array2: <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
my_array3 = np.array([[1,2,3,4],[5,6,7,8]])
print('Shape of my_array3:', my_array3.shape)
print('Size of my_array3:', my_array3.size)
print('Data types of my_array3:', my_array3.dtype)

# The size is the number of elements in the array

Shape of my_array3: (2, 4)
Size of my_array3: 8
Data types of my_array3: int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [4]:
# already defined first and second inputs
num_samples = 100
num_features = 17

random_data = np.random.random((num_samples, num_features))
random_data.shape

(100, 17)

---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [5]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

image_data = np.random.random((num_images, num_rows, num_cols, num_channels))
image_data.shape

(100, 256, 256, 3)

---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [6]:
my_array4 = np.random.randint(0, 10, (3,2))

print(my_array4)
print('1. Shape:', my_array4.shape)
print('2. Sum of elements:', my_array4.sum())
print('3. Sum of columns:', my_array4.sum(0))
print('4. Sum of rows as floats:', my_array4.sum(1).astype('float16'))
print('5. First row of array:', my_array4[0])
print('6. Second row of array:', my_array4[1])
print('7. Element at position (1,0):', my_array4[1,0])
# Set value at (2,1) to 10
my_array4[2,1] = 10
print('8. Set element at (2,1) to 10:')
print(my_array4)
print('9. Loop over elements:')
for x in np.nditer(my_array4):
    print(x, end=' ')


[[5 5]
 [6 3]
 [3 6]]
1. Shape: (3, 2)
2. Sum of elements: 28
3. Sum of columns: [14 14]
4. Sum of rows as floats: [10.  9.  9.]
5. First row of array: [5 5]
6. Second row of array: [6 3]
7. Element at position (1,0): 6
8. Set element at (2,1) to 10:
[[ 5  5]
 [ 6  3]
 [ 3 10]]
9. Loop over elements:
5 5 6 3 3 10 

You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) empty numpy array
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [19]:
print('1. Pixel array:')
print(np.random.randint(0, 2, (3,2)))
print('2. Years array:', np.arange(1991, 2018, 1))
print('3. Empty array:', np.empty([3, 5, 10]))
print('4. Array of ones:')
print(np.ones((3, 5, 10), dtype=int))
print('5. Array of constants:', np.ones(10, dtype=int) * 5)
print('6. Array of normal distribution random numbers:')
print(np.random.normal(0, 1, 10))

1. Pixel array:
[[1 1]
 [0 0]
 [1 1]]
2. Years array: [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
3. Empty array: [[[6.94350680e-310 6.94350680e-310 4.65082059e-310 4.65082059e-310
   6.94350523e-310 6.94350660e-310 6.94350523e-310 6.94350662e-310
   6.94350666e-310 6.94350666e-310]
  [6.94350666e-310 6.94350666e-310 6.94350666e-310 6.94350336e-310
   6.94350666e-310 6.94350660e-310 6.94350666e-310 6.94350336e-310
   6.94350529e-310 6.94350648e-310]
  [6.94350529e-310 6.94350522e-310 6.94350645e-310 6.94350648e-310
   6.94350522e-310 6.94350646e-310 6.94350660e-310 6.94350457e-310
   6.94350662e-310 6.94350659e-310]
  [6.94350662e-310 6.94350457e-310 6.94350662e-310 6.94350659e-310
   6.94350662e-310 6.94350660e-310 6.94350457e-310 6.94350662e-310
   6.94350659e-310 6.94350662e-310]
  [6.94350457e-310 6.94350662e-310 6.94350660e-310 6.94350662e-310
   6.94350660e-310 6.94350660e-310 6.94350529

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [8]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [9]:
years_3d = years.reshape((3, 3, 3))
print('1. 3 nested arrays - years_3d:')
print(years_3d)
print('Shape of years_3d:', years_3d.shape)
print('\n')

years_1d = np.ravel(years_3d)
print('2. Flatten years_3d - years_1d:')
print(years_1d)
print('Shape of years_1d:', years_1d.shape)
print('\n')

years_2d = np.expand_dims(years_1d, axis=0)
print('3. Insert new axis to front of years_1d - years_2d:')
print(years_2d)
print('Shape of years_2d:', years_2d.shape)
print('\n')

years_1d = np.squeeze(years_2d)
print('4. Remove 1st axis from years_2d - years_1d:')
print(years_1d)
print('Shape of years_1d:', years_1d.shape)


1. 3 nested arrays - years_3d:
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
Shape of years_3d: (3, 3, 3)


2. Flatten years_3d - years_1d:
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape of years_1d: (27,)


3. Insert new axis to front of years_1d - years_2d:
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
Shape of years_2d: (1, 27)


4. Remove 1st axis from years_2d - years_1d:
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape of years_1d: (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [10]:
a = np.random.randint(0, 11, (3,3))
b = np.random.randint(0, 11, (3,3))
c = np.random.randint(0, 11, (1,3))

print(f'Example 1\n{"-"*20}\nOriginal arrays:\n a:\n{a}\n Shape = {a.shape}\n b:\n{b}\n Shape = {b.shape}\n ')
concat_1 = np.concatenate((a, b), axis=0)
stack_1 = np.stack((a, b), axis=0)
print(f'Concat on axis 0:\n{concat_1}\n Shape = {concat_1.shape}')
print(f'Stack on axis 0:\n{stack_1}\n Shape = {stack_1.shape}')
print('\n')

print(f'Example 2\n{"-"*20}\nOriginal arrays:\n a:\n{a}\n Shape = {a.shape}\n b:\n{b}\n Shape = {b.shape}\n ')
concat_2 = np.concatenate((a, b), axis=1)
stack_2 = np.stack((a, b), axis=1)
print(f'Concat on axis 1:\n{concat_2}\n Shape = {concat_2.shape}')
print(f'Stack on axis 1:\n{stack_2}\n Shape = {stack_2.shape}')
print('\n')

print(f'Example 3\n{"-"*20}\nOriginal arrays:\n a:\n{a}\n Shape = {a.shape}\n b:\n{b}\n Shape = {b.shape}\n ')
concat_3 = np.concatenate((a, b), axis=None)
stack_3 = np.stack((a, b), axis=2)
print(f'Concat on axis None:\n{concat_3}\n Shape = {concat_3.shape}')
print(f'Stack on axis 2:\n{stack_3}\n Shape = {stack_3.shape}')
print('\n')

print(f'Example 4\n{"-"*20}\nOriginal arrays:\n a:\n{a}\n Shape = {a.shape}\n c:\n{c}\n Shape = {c.shape}\n ')
concat_4 = np.concatenate((a, c), axis=0)
stack_4 = np.stack((a[[0]], c), axis=0)
print(f'Concat on axis 0:\n{concat_4}\n Shape = {concat_4.shape}')
print(f'Stack 1st row of a on c on axis 0:\n{stack_4}\n Shape = {stack_4.shape}')


Example 1
--------------------
Original arrays:
 a:
[[ 0  7  0]
 [ 5  2  3]
 [10  4 10]]
 Shape = (3, 3)
 b:
[[ 2  2  5]
 [ 9  6  4]
 [ 9 10  8]]
 Shape = (3, 3)
 
Concat on axis 0:
[[ 0  7  0]
 [ 5  2  3]
 [10  4 10]
 [ 2  2  5]
 [ 9  6  4]
 [ 9 10  8]]
 Shape = (6, 3)
Stack on axis 0:
[[[ 0  7  0]
  [ 5  2  3]
  [10  4 10]]

 [[ 2  2  5]
  [ 9  6  4]
  [ 9 10  8]]]
 Shape = (2, 3, 3)


Example 2
--------------------
Original arrays:
 a:
[[ 0  7  0]
 [ 5  2  3]
 [10  4 10]]
 Shape = (3, 3)
 b:
[[ 2  2  5]
 [ 9  6  4]
 [ 9 10  8]]
 Shape = (3, 3)
 
Concat on axis 1:
[[ 0  7  0  2  2  5]
 [ 5  2  3  9  6  4]
 [10  4 10  9 10  8]]
 Shape = (3, 6)
Stack on axis 1:
[[[ 0  7  0]
  [ 2  2  5]]

 [[ 5  2  3]
  [ 9  6  4]]

 [[10  4 10]
  [ 9 10  8]]]
 Shape = (3, 2, 3)


Example 3
--------------------
Original arrays:
 a:
[[ 0  7  0]
 [ 5  2  3]
 [10  4 10]]
 Shape = (3, 3)
 b:
[[ 2  2  5]
 [ 9  6  4]
 [ 9 10  8]]
 Shape = (3, 3)
 
Concat on axis None:
[ 0  7  0  5  2  3 10  4 10  2  2  5  9 

---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [11]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [12]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [13]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [14]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [15]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.6498928 , 0.55493883, 0.13314519, 0.86557862],
       [0.3229546 , 0.41458647, 0.07016092, 0.76583453],
       [0.07884411, 0.69312411, 0.79234896, 0.19591758],
       [0.24148358, 0.22399551, 0.63243409, 0.06205178],
       [0.00847045, 0.41591398, 0.75004022, 0.22669297],
       [0.51385244, 0.91647185, 0.7006362 , 0.52420164],
       [0.02333278, 0.72098503, 0.5145332 , 0.12702574],
       [0.10330266, 0.29151907, 0.2910087 , 0.96679331],
       [0.70639668, 0.71151195, 0.5293661 , 0.53715354],
       [0.85168963, 0.22975114, 0.62877483, 0.00541378]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [16]:
np.random.seed(seed=1)

col_means = np.mean(my_array, axis=0, keepdims=True)
col_stddev = np.std(my_array, axis=0, keepdims=True)

print('Mean for columns:', col_means)
print('Standard deviation for columns:', col_stddev)
print('Standardized values for my_array:')
print((my_array  - col_means) / col_stddev)

Mean for columns: [[0.35002197 0.51727979 0.50424484 0.42766635]]
Standard deviation for columns: [[0.29423471 0.22613999 0.24213209 0.33384773]]
Standardized values for my_array:
[[ 1.01915517  0.16652977 -1.53263307  1.3117126 ]
 [-0.09199246 -0.45411397 -1.79275666  1.01294138]
 [-0.9216379   0.77759056  1.18986343 -0.69417507]
 [-0.3688837  -1.29691476  0.52941866 -1.09515366]
 [-1.16081315 -0.44824366  1.01512928 -0.60199116]
 [ 0.55680198  1.76524313  0.81109182  0.28915964]
 [-1.11030133  0.90079266  0.0424907  -0.90053213]
 [-0.83851193 -0.99832289 -0.88066039  1.61488879]
 [ 1.21119193  0.85890229  0.10375023  0.32795548]
 [ 1.7049914  -1.27146313  0.51430599 -1.26480586]]


----
#### <span style="color:chocolate">Bonus question:</span> Advanced (20 points)

Consider the following image:

In [17]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by using a border of size 2;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [18]:
def crop_image(image_array, border_size):
    '''
    Crop an image array by removing the given border size rows and columns
    from the provided array.
    
    ARGS
    image_array (np array): original image 2D array
    border_size (int): number of units to crop 

    RETURN
    numpy 2D array
    '''
    orig_rows = image_array.shape[0]
    new_rows = orig_rows - border_size
    orig_cols = image_array.shape[1]
    new_cols = orig_cols - border_size
    
    return image_array[border_size:new_rows, border_size:new_cols]

print('1. Crop border size of 1:')
cropped_image = crop_image(my_image, 1)
print(cropped_image)
print('\n')

print('2. Crop border size of 2:')
cropped_image = crop_image(my_image, 2)
print(cropped_image)
print('\n')

print('3. Reverse column order:')
print(my_image[:,::-1])
print('\n')

print('4. Set even elements to 0.5:')
# Use divmod to avoid the rounding errors when dividing floats
new_image = np.where(divmod(my_image, 2)[0] == 0, .5, my_image)
print(new_image)


1. Crop border size of 1:
[[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]


2. Crop border size of 2:
[[0.48]]


3. Reverse column order:
[[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]


4. Set even elements to 0.5:
[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]
